site_name: BlackCat Monitor 


pages:
    - Home: index.md
    - Install: install.md

theme:
  name: 'material'

markdown_extensions:
  - admonition

google_analytics: ['UA-20193061-1', 'blackcat.orx.me']